mahasiswa/urls.py
from django.conf.urls import url
from .views import index, profile, edit, add_status, delete_status, add_bot_friends, delete_friend, search_friend, update
from .custom_auth import auth_login, auth_logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^update/', update, name='update'),
    url(r'^edit/$', edit, name='edit'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id_status>\d+)/$', delete_status, name = 'delete_status'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
    url(r'^add_bot_friends', add_bot_friends, name='add_bot_friends'),
    url(r'^delete_friend/(?P<id>\d+)/$', delete_friend, name = 'delete_friend'),
    url(r'^search_friend', search_friend, name = 'search_friend'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import mahasiswa.urls as mahasiswa
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mahasiswa/', include(mahasiswa,namespace='mahasiswa')),
    url(r'^$', RedirectView.as_view(url='mahasiswa/', permanent=True), name='$  '),
]

mahasiswa/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=250, default="Empty")
    npm = models.CharField(max_length=15, default="Empty")
    angkatan = models.IntegerField(default=2016,
        validators=[MaxValueValidator(2018), MinValueValidator(1900)])
    npm = models.CharField(max_length=15, default="Empty")
    email = models.TextField(default="Empty")
    link = models.TextField(default="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png")
    linkedIn = models.TextField(default="Empty")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    expert = models.CharField(max_length=300, default="Java, C++")

# class Expertise(models.Model):
#     user = models.ForeignKey(User)
#     expert = models.CharField('Expertise', max_length=27)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

class Status(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    user_id = models.CharField(max_length=15, default="1606917922")
    user_name = models.CharField(max_length=250, default="Empty")

mahasiswa/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'What\'s on your mind?'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

mahasiswa/views.py
from __future__ import unicode_literals
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from .models import User, Status
from .forms import Status_Form
from .forms_friend import Friend_Form
from random import randint
from django.core import serializers
import json
# Create your views here.

response = {}
def index(request): # pragma: no cover
    # response['form'] = "aaaa" #Status_Form
    if 'user_login' in request.session:
        response['status_form'] = Status_Form
        html = 'tugas2/tables/status.html'
        render(request, html, response)
        return HttpResponseRedirect(reverse('mahasiswa:profile'))
    else:
        html = 'tugas2/session/login.html'
        return render(request, html, response)

def add_status(request): # pragma: no cover
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'],user_id=request.session['kode_identitas'], user_name=request.session['user_login'])
        status.save()
        #html ='lab_4/form_result.html'
        return HttpResponseRedirect('/mahasiswa/')
    else:
        return HttpResponseRedirect('/mahasiswa/')

def delete_status(request, id_status): # pragma: no cover
    status = Status.objects.get(pk = id_status)
    status.delete()
    return HttpResponseRedirect('/mahasiswa/')

@csrf_exempt
def update(request):
    if request.method == 'POST':
        for key in request.session.items():
            print (key)
        
        kode_identitas = request.session['kode_identitas']
        profile = User.objects.get(pk=1)
        fullname = request.POST['full_name']
        url_linkedin = request.POST['url_linkedin']
        picture_url = request.POST['picture_url']
        email = request.POST['email']
        profile.name = fullname
        profile.linkedIn = url_linkedin
        profile.link = picture_url
        profile.email = email
        profile.save()
        return HttpResponseRedirect(reverse('mahasiswa:profile'))


def profile(request): # pragma: no cover
    profile_tampilan = User(name="Empty", email="Empty", link="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png")
    profile_tampilan.save()
    profile = User.objects.get(pk=1)
    splitexp = profile.expert.split(',')
    status = Status.objects.filter(user_id=request.session['kode_identitas'])
    response = {'profile': profile}
    response['friend_list'] = User.objects.filter(~Q(name="Empty"))
    response['form'] = Status_Form
    response['form2'] = Friend_Form
    response['model'] = status
    html = 'tugas2/session/profile.html'
    profile.name = request.session['user_login']
    friend = User.objects.filter(~Q(name = "Empty"))
    response['friend_list'] = friend
    response['splitexp'] = splitexp
    html = 'tugas2/session/profile.html'
    for key in request.session.items():
        print (key)
    profile.npm = request.session['kode_identitas']
    response['jml_status'] = len(status)
    return render(request, html, response)

def edit(request): # pragma: no cover
    profile_tampilan = User(name="Empty", email="Empty", link="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png")
    profile_tampilan.save()
    profile = User.objects.get(pk=1)
    response= {'profile': profile}
    status = Status.objects.filter(user_id=profile.npm)
    response['form'] = Status_Form
    response['model'] = status
    html = 'tugas2/session/profile.html'
    for key in request.session.items():
        print (key)
    profile.name = request.session['user_login']
    profile.npm = request.session['kode_identitas']
    response['jml_status'] = len(status)
    html = 'tugas2/session/edit.html'
    return render(request, html, response)

# def friend_List(request):
#     add_bot_friends(request)
#     list_Friend = User.objects.all()
#     response['friend_list'] = list_Friend
#     html = "tugas2/tables/mahasiswa/tabel_teman.html"
#     return render(request, html, response)

def add_bot_friends(request): # pragma: no cover
    print(request.method)
    if request.method == "POST" :
        nama = ["Baba", "Bubu", "kolal", "Cinta", "bubu", "Bibi", "Ade", "huhu", "Kak Pewe", "Asdos"]
        npm = ["1092872138", "21378871", "213672131", "1283712", "172633", "1233412", "1233123", "123321342", "12342141", "1234564"]
        keahlian = ["Java", "Python", "C++", "HTML", "C#"]
        for x in range(10):
            friend = User(name=nama[x], npm=npm[x], expert=keahlian[randint(0,4)])
            friend.save()
            print("Berhasil tambah")
        print("babababa")
        return HttpResponseRedirect('/mahasiswa/')
    else:
        return HttpResponseRedirect('/mahasiswa/')


def delete_friend(request, id): # pragma: no cover
    friend = User.objects.get(pk = id)
    friend.delete()
    return HttpResponseRedirect('/mahasiswa/')

def search_friend(request): # pragma: no cover
    form = Friend_Form(request.POST or None)
    users = User.objects.filter(name="Asdos")
    if(request.method == 'POST' and form.is_valid()):
        sesuatu = request.POST["Filter"]
        if sesuatu == "Nama":
            users = User.objects.filter(name = request.POST["search"])
        elif sesuatu == "NPM":
            users = User.objects.filter(npm=request.POST["search"])
        elif sesuatu == "Angkatan":
            users = User.objects.filter(angkatan=request.POST["search"])
        elif sesuatu == "Keahlian":
            users = User.objects.filter(expert=request.POST["search"])
        html = 'tugas2/tables/mahasiswa/searchsct.html'
        response["friends"] = users
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/mahasiswa/profile/')

# def get_user_data(sesuatu, id):

#     data = []
#     for user in users:
#         temp = {}
#         temp["name"] = user.name
#         temp["npm"] = user.npm
#         temp["angkatan"] = user.angkatan
#         temp["keahlian"] = user.expertise
#         data.append(temp)
#     return json.dumps(data)

mahasiswa/templates/tugas2/tables/friends.html
<div class="panel panel-info">
    <div class="panel-body">
            <div class="search">
                <h2>Search Friend</h2>
            	<form style="width: 100%" method="POST" action="{% url 'mahasiswa:search_friend' %}">
                {% csrf_token %}
                {{ form2 }}
                <br>
                <table class="table">
                  <td><input type="radio" name="Filter" value="Nama"> Nama<br></td>
                  <td><input type="radio" name="Filter" value="NPM"> NPM<br></td>
                  <td><input type="radio" name="Filter" value="Angkatan"> Angkatan <br></td>
                  <td><input type="radio" name="Filter" value="Keahlian"> Keahlian<br></td>
                  <td><input type="radio" name="Filter" value="Level"> Level<br></td>
                  </table>
                    <input class="btn btn-lg " style="float: right;" type="submit" value="Search" />
                </form>
            </div>

            <div class="tabel">
                {% include 'tugas2/tables/mahasiswa/tabel_teman.html' %}
            	<form  method="POST" action="{% url 'mahasiswa:add_bot_friends' %}">
            	{% csrf_token %}
    				<input class="btn btn-lg btn-block btn-info" type="submit" value="Add Bot Friends" />
				</form>
            	
            </div>
    </div>
</div>
<script>
// If user clicks anywhere outside of the modal, Modal will close


</script>

mahasiswa/templates/tugas2/tables/history.html
<div class="panel panel-info">
        <div class="panel-body">
           <h1>INI HISTORY</h1>
        </div>
    </div>

mahasiswa/templates/tugas2/tables/profile.html
<div class="panel panel-info">
    <div class="panel-body">
            <div class="biodata">
                    <table align="left" style="text-align: left">
                        <tr><td class="subject" >Name</td><td class="value" >: {{profile.name}}</td></tr>
                        <tr><td class="subject" >NPM</td><td class="value" >: {{ profile.npm }}</td></tr>
                        <tr><td class="subject" >Expertise</td><td class="value">: {% for ii in splitexp %}<span id="expert" class="expert">{{ii}}</span>{% endfor %}</td></tr>
                        <tr><td class="subject" >Email</td><td class="value" >: {{profile.email}}</td></tr>
                        <tr><td class="subject" >LinkedIn Profile</td><td class="value" >: {{profile.linkedIn}}</td></tr>
                    </table>
            </div>
    </div>
</div>

mahasiswa/templates/tugas2/tables/status.html
<div class="panel panel-info">
        <div class="panel-body">

<section name="input-list" id="input-list">
    <div class="container">
    	<form id="form" method="POST" action="{% url 'mahasiswa:add_status' %}" style="width:100%;">
            <h2>Update Status</h2>
            {% csrf_token %}
            {{ form }}
            <br>
            <input id="post-button" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">Timeline</h2>
        <div class="flex">
        {% if model %}
        	{% for data in model %}
          <div class="flex-item status-flex">
            <a href="/mahasiswa/delete_status/{{ data.id }}">
          <div class="delete-button" data-id={{data.id}}}>x</div>
        </a>
          <div class="postee">
          <img class="img depe" src = "https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png" width="50px">
          {{ data.user_name }}
        </div>
				  <div class="isi-status">{{data.description}}</div>
				  <div class="date-added" id="date-added">
            {{data.created_date}}
          </div>
        </div>
        	{% endfor %}
        {% else %}
        	<div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada post di timeline.
            </div>
        {% endif %}
      </div>
    </div>
</section>
        </div>
    </div>